### ISSUE TITLE
Poster IPs aren't saved.

### ISSUE THREAD

**Issue by ultimatenyymi** [314parley/Haruko#5]
I tried to ban some users from my board, but when i did the ip field of the banning form was empty. Then i tried to check if i even could see the ips of posters and i couldn't. After that i checked my "posts" table from MySql database and the ip column was empty. What could be the reason for this problem?

**Comment by 314parley** [comment]
It might be because 314chan is behind CloudFlare. try finding all references of $_SERVER["HTTP_CF_CONNECTING_IP"] and replace them with  $_SERVER['REMOTE_ADDR']

**Comment by ultimatenyymi** [comment]
Thanks.
